various improvement for reloading

diff --git a/multipleMining b/multipleMining
--- a/multipleMining
+++ b/multipleMining
@@ -1,4 +1,58 @@
-echo "HUSH - XVG"
+#!/bin/bash
 
-mine -c HUSH_S -d 3,4,5,6 >> /var/log/mining.log &
-mine -c XVG_17 -d 0,1,2  >> /var/log/mining.log &
+################################################################################
+### SCRIPT_DIR is the location the script
+SCRIPT_DIR="`dirname \"$0\"`"                 # relative
+SCRIPT_DIR="`( cd \"$SCRIPT_DIR\" && pwd )`"  # absolutized and normalized
+if [ -z "$SCRIPT_DIR" ] ; then
+    # error; for some reason, the path is not accessible
+    # to the script (e.g. permissions re-evaled after suid)
+    exit 1  # fail
+fi
+
+source $SCRIPT_DIR/FUNCTIONS
+
+################################################################################
+
+#trap ctrl_c INT
+
+usage ()
+{
+cat << EOF
+usage: $0 config_file
+
+This script launch several miners on different cards
+
+example format of config file:
+3 GBX
+4 ZCL
+will launch GBX miner on first 3 cards, followed by ZCL miner on 4 cards
+EOF
+}
+
+
+function ctrl_c()
+{
+	echo "Terminating..."
+	exit 0
+}
+
+
+if [ -z "$1" ]; then
+	usage
+	exit 1
+fi
+
+
+#while :
+
+index=0
+while read line;
+do
+	stringarray=($line)
+	devices=$(devices_with_coma $index ${stringarray[0]})
+	launch_miner ${stringarray[1]} $devices 1
+	index=`expr $index + ${stringarray[0]}`
+done < $1
+
+
